# Compiler
CXX = g++

# Project
TARGET = traffic_sim

# Directories
SRC_DIR = src
BUILD_DIR = build

# SDL3 paths
SDL_INC = E:/SDL3/SDL3-3.2.28/x86_64-w64-mingw32/include
SDL_LIB = E:/SDL3/SDL3-3.2.28/x86_64-w64-mingw32/lib

# Flags
CXXFLAGS = -std=c++17 -Wall -I$(SDL_INC)
LDFLAGS  = -L$(SDL_LIB) -lSDL3

# Source files
SRCS = $(SRC_DIR)/main.cpp \
       $(SRC_DIR)/queue.cpp \
       $(SRC_DIR)/vehicle.cpp

# Output
OUT = $(BUILD_DIR)/$(TARGET).exe

# Build rules
all: $(OUT)

$(OUT): $(SRCS)
	@mkdir -p $(BUILD_DIR)
	$(CXX) $(SRCS) $(CXXFLAGS) $(LDFLAGS) -o $(OUT)

clean:
	rm -rf $(BUILD_DIR)
